### ISSUE TITLE
Get the xilinx_bitstream.ksy into the Kaitai format gallery.

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#105]
@kc8apf put together a [Kaitai Struct language](http://kaitai.io/#what-is-it) description of the Xilinx Bitstream format here -> https://github.com/SymbiFlow/prjxray/blob/master/docs/xilinx_bitstream.ksy

It would be great to get this description into the Kaitai Format Gallery here -> http://formats.kaitai.io/

**Comment by kc8apf** [comment]
Kaitai Struct only support purely stateless parsing. That only works up to the packet layer for Xilinx bitstreams.  As there are now both C++ (prjxray) and Rust (gaffe) parsers that work up through config frames, the KSY only serves to mislead someone that Kaitai Struct works for this purpose.  I'll remove the KSY from prjxray.
