### ISSUE TITLE
Where's arty.py?

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/prjxray#1067]
Mentioned in: [minitests/litex/README.md](https://github.com/SymbiFlow/prjxray/blob/3783e7b2e3259906cf03e1e73cfc539713d5d9bd/minitests/litex/README.md)

**Comment by HackerFoo** [comment]
Also, what else do I need to recreate the generated files? Which version of LiteX?

**Comment by mkurc-ant** [comment]
https://github.com/SymbiFlow/prjxray/pull/1068

**Comment by mkurc-ant** [comment]
The PR https://github.com/SymbiFlow/prjxray/pull/1068 was merged. Closing.
