### ISSUE TITLE
Zynq7 build unstable

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#1246]
There are some instabilities regarding the tilegrid fuzzer that should be solved.

For reference, here is an error of a particular run: https://github.com/SymbiFlow/prjxray/pull/1227#issuecomment-587601068

**Comment by acomodi** [comment]
There have been periodic instabilities on the zynq7 build. The ones that did show up for now are the following:

Bit collisions:
- https://github.com/SymbiFlow/prjxray/pull/1253#issuecomment-590810303

Fuzzer failures:
- https://github.com/SymbiFlow/prjxray/pull/1227#issuecomment-587601068

The latter one is most probably already solved by increasing the number of specimens.

**Comment by mkurc-ant** [comment]
Again, instability: https://github.com/SymbiFlow/prjxray/pull/1307

**Comment by tcal-x** [comment]
Also, [#1313](https://github.com/SymbiFlow/prjxray/pull/1313).

**Comment by mithro** [comment]
```
Checking zynq7 database
============================
Checking individual .db...
segbits_*.db: 33 okay
mask_*.db: 39 okay
Checking aggregate dir...
ERROR: 1 collisions
  0042229a_044_27: had INT_R_X69Y22.INT_R.IMUX25.LOGIC_OUTS18, got CLBLM_R_X69Y22.CLBLM_R.SLICEL_X1.BLUT.INIT[16]
Traceback (most recent call last):
  File "utils/checkdb.py", line 190, in <module>
    main()
  File "utils/checkdb.py", line 186, in main
    run(args.db_root, args.part, verbose=args.verbose)
  File "utils/checkdb.py", line 172, in run
    check_tile_overlap(db, verbose=verbose)
  File "utils/checkdb.py", line 148, in check_tile_overlap
    raise ValueError("%s collisions" % len(collisions))
ValueError: 1 collisions
Makefile:172: recipe for target 'db-check-zynq7' failed
make: *** [db-check-zynq7] Error 1
```
