### ISSUE TITLE
Add license automated check in Travis

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#1306]
There should be an automated test to check that all source code in the project has the SPDX Identifier, and, in case of third_party tools, that the LICENSE file is present.

[This script](https://github.com/SymbiFlow/fpga-tool-perf/blob/f8d143b73f670eea5efdbe96f1236d82998c896e/.github/travis/check_license.sh) can be used and changed accordingly to the source file-types by adding/removing the correct extensions

**Comment by tmichalak** [comment]
This has been done. Closing.

**Comment by mithro** [comment]
This was done by https://github.com/SymbiFlow/prjxray/pull/1301
