### ISSUE TITLE
Timing fuzzer: min corners tend towards 0 delay

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#136]
When solving for the minimum delay, an ideal min delay is equal to the max delay. However, its legal to move a delay as low as 0. The timing very disproportionately assigns minimum delays to 0 vs what is expected to be realistic. For example:

```
Corner fast_max
  pips: 2882 / 8482 solved, 3978 / 8482 covered
Corner fast_min
  pips: 40 / 8482 solved, 3978 / 8482 covered
```

Investigate what is causing this pressure, and if it can be fixed.

**Comment by mithro** [comment]
@kgugala / @litghost - I think this is no longer relevant with the new way we get timing data?

**Comment by kgugala** [comment]
@mithro I think this issue is related to wires delays. We still use the same method for calculating the wires delays, so it may be still relevant

**Comment by litghost** [comment]
> @kgugala / @litghost - I think this is no longer relevant with the new way we get timing data?

Ya, this is no longer relevant.
