### ISSUE TITLE
tilegrid.json: Update utilities to use latest format

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#140]
The tilegrid.json conversion was incomplete, the following utilities relied on the old format:

- fasm2frame.py
- segprint2fasm.py
- segprint.py

#139 adds bridge fields and code to solve this in the short term, but in the long term utilities should likely converge.  Suggestion to resolve is to add cabilities to the prjxray library that hide the underlying file format from the various utilities, and expose a usable API for interacting with the underlying database.

**Comment by mcmasterg** [comment]
https://github.com/SymbiFlow/prjxray/pull/159 makes some progress on this

**Comment by litghost** [comment]
#167 converts fasm2frame.py and bits2fasm.py

**Comment by mcmasterg** [comment]
Close this? There's a little lingering in htmlgen, but that has a dedicated issue (https://github.com/SymbiFlow/prjxray/issues/173)

**Comment by litghost** [comment]
utils/segprint.py is not converted yet.
