### ISSUE TITLE
Add part data for all parts

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#1476]
Once #1475 is complete, populate part data for all parts that fabric documentation exists for.  #1475 should be done first to avoid duplicating all of the fabric data repeatedly.

**Comment by dnltz** [comment]
@litghost - Before I will start I have some questions:
1) Where do I know the fabric documentation exists? Because the script in settings/ exists?
2) Where do I know devices share the same fabric?
3) Any restrictions on the parts or do you want all available packages, devices and speed grades?

**Comment by litghost** [comment]
I would start with a family, e.g. "artix7".  Example:
```
get_parts -filter "FAMILY == artix7"
```

**Comment by litghost** [comment]
> * Where do I know devices share the same fabric?

I think the default is each device is a different fabric, and add a file that specifies which devices are the same fabric.  Does that make sense?

**Comment by dnltz** [comment]
Ah, that's a brilliant way to fetch all available parts, thanks!

Okay. I understood different devices share the same fabric as well. Makes absolutely sense to me now. That's also the reason for: https://github.com/SymbiFlow/prjxray/pull/1549

**Comment by dnltz** [comment]
hey @litghost, I wrote a script to populate all supported parts. Should I also extend the Makefile to roi_only all parts during the CI runs?

**Comment by litghost** [comment]
> hey @litghost, I wrote a script to populate all supported parts. Should I also extend the Makefile to roi_only all parts during the CI runs?

Yep, exactly!
