### ISSUE TITLE
module 'fasm' has no attribute 'Annotation'

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/prjxray#1519]
The definition of the named tuple `Annotation` has been removed from `fasm` as of `3a45c106f`. However, it is still used by the `fasm_disassembler.py` in prjxray eg.: https://github.com/SymbiFlow/prjxray/blob/483a89c292b5367e9f18cff21b4bcd182d81c401/prjxray/fasm_disassembler.py#L79

This makes the disassembler crash when used with the latest `fasm` (eg. in `symbiflow-xc-fasm2bels` CI).

**Comment by mithro** [comment]
FYI - @HackerFoo

**Comment by HackerFoo** [comment]
This should fix it: https://github.com/SymbiFlow/fasm/pull/40

**Comment by litghost** [comment]
This should be fixed now.
