### ISSUE TITLE
Investigate PCIE_2_1 PIPs

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#1540]
This issue is to keep track of the information on the PIPs around the PCIE_2_1 primitives for xc7 parts.

### Description

The PCIE_2_1 primitive is a hard block that is half-clock region tall and has many connections with the fabric. By investigating the device view, it results that there are some pips in the `PCIE_INT_INTERFACE` tiles which work a bit like the `BOUNCE` pips in the INT tiles.

![Screenshot from 2021-01-13 12-37-27](https://user-images.githubusercontent.com/44773360/104447511-30633800-559c-11eb-8be5-1766664befda.png)

The image above represents a section of the `PCIE_INT_INTERFACE` that displays said pips.

By further investigation, these pips seem to occupy the 27th frame of the segment in which the PCIE_2_1 primitive is, and that,  by default, the pip allows a direct connection, without *bouncing* to the additional wire before getting to the destination port.

These PIPs should likely require a pce-int-pips fuzzer.

**Comment by litghost** [comment]
Is this complete?

**Comment by acomodi** [comment]
Yes, this was done. Closing.
