### ISSUE TITLE
All output products should go into "build" dir

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#171]
Right now we dump misc output products into source directories. It would be nice to instead consistently dump all products into a unified output directory

**Comment by mcmasterg** [comment]
Following are left:
  * 051-055
  * 057, 058
  * 071-074
  * 100

**Comment by mcmasterg** [comment]
Following are left:
  * 055
  * 057, 058
  * 071-074
  * 100

**Comment by mcmasterg** [comment]
Following are left:
* 058
* 071-074

**Comment by JohnDMcMaster** [comment]
Following are left: 071-074

**Comment by mcmasterg** [comment]
nats looking at this, adding some details discussed over IRC:

```
I'd like there to only be two generated files in fuzzer directories: build, run.ok
(with the eventual goal to eliminate run.ok, but we can do that later)
This is the case on most fuzzers today, except for the three mentioned in the ticket
You will need to primarily edit the makefile, but might also need to adjust some paths in say tcl or python scripts in that directory
the idea is that if everything is moved to build, simply deleting the build dir will clean it
```

**Comment by natsfr** [comment]
Following left 072-074, I have patches but because of RAM use problem in 072 I can't test them for 072 **AND** 074 (dependent on 072).
Discussing that at the moment to figure out what to do next.

**Comment by natsfr** [comment]
Should be ok to close now

**Comment by JohnDMcMaster** [comment]
Looks like part-yaml still needs this

**Comment by JohnDMcMaster** [comment]
fixed
