### ISSUE TITLE
Create tool to patch blockram (BRAM) contents in bitstream

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#181]
Allow easy swapping of ROM / RAM contents in a bistream using only open tooling?

**Comment by mithro** [comment]
Probably need some way to produce annotations for were various RAM contents ends up?

**Comment by mithro** [comment]
Could this be another example of FASM machine parsable comments that don't end up as actual bitstream values?

**Comment by litghost** [comment]
FASM can now process BRAM data section bits correctly, so this is basically just creating a tool to convert data bits into FASM output. There needs to be section mapping of address lines to tile locations of some sort.

**Comment by mithro** [comment]
Would be good if a tool could also patch DRAM contents too!

**Comment by tmichalak** [comment]
BRAM patcher is being worked on in a separate [repo](https://github.com/SymbiFlow/prjxray-bram-patch)
