### ISSUE TITLE
Duplicate `export XRAY_ROI` value in artix7 settings.sh file

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#201]
The [artix7 settings.sh file](https://github.com/SymbiFlow/prjxray/blob/master/database/artix7/settings.sh) has the following;
https://github.com/SymbiFlow/prjxray/blob/5e1760e8ec474a3171dae09ebeb98a813b34deca/database/artix7/settings.sh#L3

and then a little further down;
https://github.com/SymbiFlow/prjxray/blob/5e1760e8ec474a3171dae09ebeb98a813b34deca/database/artix7/settings.sh#L6-L7

I assume it means the value *actually* being used is the second one and we can just remove the first one.

**Comment by mcmasterg** [comment]
oops, this crept in during a merge issue a while back
