### ISSUE TITLE
BRAM TDP vs SDP

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#208]
I'm unclear if SDP is a real bitstream mode or just a simplified user presentation. Notes:
- BRAM18 SDP supports 72 bit width. But I think this is just A/B combined
- UG says "block RAM primitives and the SDP macro"
- When I diffed, I got two bits, but at least one of them was identified as probably WRITE_MODE_A_NO_CHANGE

segprint isn't  working well right now for bram. Once its fixed, follow up with this and confirm these bits aren't important

Other: this is also getting shelved right now due to relatively low perceived return on investment vs looking at IOB

**Comment by mithro** [comment]
@litghost Did you figure this out recently?

**Comment by litghost** [comment]
I agree with @JohnDMcMaster assessment.  The SDP/TDP appears to be a synthesis change, rather than a bit.
