### ISSUE TITLE
Get vagrant to also create docker image

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#23]
@kc8apf create a vagrant script here -> https://github.com/SymbiFlow/prjxray/tree/master/vagrant

It would be good if this could be used to create a docker image (or if a docker version was created).

The only complication is that `/opt/Xilinx` should probably be in a separate container to the rest of the output so that the docker image can be shared without accidentally also sharing Vivado.

**Comment by kc8apf** [comment]
Docker image for a standardized development environment can be built from https://github.com/SymbiFlow/prjxray-dev-env.  Resulting images may not be distributed due to Vivado's licensing terms.
