### ISSUE TITLE
Review fuzzer segmatch -m/-M options

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#318]
See: https://github.com/SymbiFlow/prjxray/pull/317

Pending scaling those results up to real runs, we should apply the results to other fuzzers. Most right now use nothing or "-m 5 -M 15", either of which is probably unsafe.

**Comment by tmichalak** [comment]
I am not aware of any issues related to the current choice of the segmatch flags. I guess this can be closed for now.
