### ISSUE TITLE
Clean up .gitignores

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#344]
We have tailing newlines and other issues. Suggest not worrying too much about this until build dirs are standardized (https://github.com/SymbiFlow/prjxray/issues/171)

**Comment by JohnDMcMaster** [comment]
FYI a recent patch deleted most of the .gitignore files

**Comment by elmsfu** [comment]
@litghost Please leave a comment when you close an issue. Is this issue stale from pre-cmake build?

**Comment by litghost** [comment]
This issue is very stale, and I believe was already handled long ago.
