### ISSUE TITLE
Add support for Zynq parts

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#377]
The Zynq parts have the same fabric as the Artix-7 / Kintex-7. This should make it pretty easy to apply the same fuzzing approach to these parts.

We should add support for them!

**Comment by mithro** [comment]
@kgugala has started work on this.

**Comment by mithro** [comment]
@kgugala - Can you put the current status here?

**Comment by mithro** [comment]
- [ ] Add settings.sh for a Zynq part
 - [ ] Check the status of each of the fuzzers
 - [ ] Create symbiflow-arch-defs for Zynq part

**Comment by litghost** [comment]
I recommend fixing https://github.com/SymbiFlow/symbiflow-arch-defs/issues/298 before integrating with symbiflow-arch-defs.  This is with the assumption that the tile types, site types and definitions for zync and artix7 are the same.

**Comment by mithro** [comment]
@kgugala This is pretty much done now right?

**Comment by kgugala** [comment]
@mithro yes it is. I think we can close this issue and create more specific ones for the Zynq related stuff
