### ISSUE TITLE
Merge intpips/Makefile and int_loop.mk

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#407]
These used to be pretty different, but now they are almost the same and need to be kept in sync (see for example https://github.com/SymbiFlow/prjxray/pull/406). Most of the divergences are because of things like intpips needing parallelism that wasn't necessary in others. There should only be a few flags that intpips needs to override in int_loop.mk after the paralleism is brought in

**Comment by tmichalak** [comment]
This has already been done. Closing.
