### ISSUE TITLE
Document PLL config bits for Artix-7

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/prjxray#413]
Related: https://github.com/SymbiFlow/prjxray/issues/46

**Comment by litghost** [comment]
For an update on this, first PR is in https://github.com/SymbiFlow/prjxray/pull/912, and a second PR fuzzing the interconnect is on its way.

Current status:
 - Total (estimated) number of bits belongs to the PLL: ~209
 - Total remaining bits with current fuzzer: 112

I'm hoping to find another chunk of bits, but it may take a bit.
