### ISSUE TITLE
Add documentation for site_type_XXX.json files

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#434]
Example documentation -> https://prjxray.readthedocs.io/en/latest/format/tile.html#

See an example here -> 

https://github.com/SymbiFlow/prjxray-db/blob/aa178c3e2f9a90436c253cd81c488fe6b128d081/artix7/site_type_SLICEL.json#L1-L694

**Comment by tmichalak** [comment]
Some information on the tile_types has been added to the [docs](https://symbiflow.readthedocs.io/projects/prjxray/en/latest/dev_database/common/site_type.html). Closing.
