### ISSUE TITLE
Add documentation for tile_type_XXX.json files

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#435]
See also  #434.

See https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/tile_type_CLBLL_L.json for an example.
See https://prjxray.readthedocs.io/en/latest/format/tile.html# for were the documentation should end up.

**Comment by tmichalak** [comment]
Some information on the tile_types has been added to the [docs](https://symbiflow.readthedocs.io/projects/prjxray/en/latest/dev_database/common/tile_type.html). Closing.
