### ISSUE TITLE
buggy hclk_mask entries in current DB

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/prjxray#451]
see:
https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/mask_hclk_l.db#L105
https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/mask_hclk_r.db#L105

**Comment by mcmasterg** [comment]
File ends:

```
bit 05_29
bit 05_30
bit 05_31
bit <0
bit candidates>
```

should only have entries like the first three, not the last two

**Comment by mithro** [comment]
This looks like it has been fixed. These incorrect entries at the end of the file no longer appear?
