### ISSUE TITLE
Zynq: understand PS7 instantiation

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#453]
Being worked on by @acomodi

**Comment by mithro** [comment]
@acomodi Is this all done now?

**Comment by kgugala** [comment]
As far as I know we understand base addresses and bits of the PS interconnections. We still don't understand which PS pin goes where (e.g which GPIO goes to which interconnect etc)

**Comment by tmichalak** [comment]
We support PS7 in arch-defs for some time already. Closing.
