### ISSUE TITLE
Regression in CLB bits CLBLM CARRY4.ACY0

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#466]
Before:
> CLBLM_R.SLICEL_X1.CARRY4.ACY0 31_14

After:
> CLBLM_R.SLICEL_X1.CARRY4.ACY0 31_01 31_04 31_14 31_15

Previous definition appeared to be correct, relatively sure the new definition is wrong.

https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/segbits_clblm_l.db#L169

Interestingly enough, BCY0, CCY0 and DCY0 all appear correct.

**Comment by mcmasterg** [comment]
I think @kgugala is aware of this and working on a fix

**Comment by mcmasterg** [comment]
this is actually a duplicate of https://github.com/SymbiFlow/prjxray/issues/466

**Comment by tmichalak** [comment]
@mcmasterg I think you meant that this is a duplicate of #456.
Anyhow I am looking into it
