### ISSUE TITLE
051_imuxlout hangs after 5/specimen_020 for zynq

### ISSUE THREAD

**Issue by Fatsie** [SymbiFlow/prjxray#472]
make in fuzzers hangs on after build/5/specimen_020 in 051_imuxlout, last lines of the output are:

> Dumping pips.
> INFO: [Common 17-206] Exiting Vivado at Wed Jan  9 20:14:35 2019...
> ++ fgrep CRITICAL vivado.log
> \+ test -z ''
> \+ for x in 'design*.bit'
> \+ /home/verhaegs/eda/code/prjxray/build/tools/bitread --part_file /home/verhaegs/eda/code/prjxray/database/zynq7/xc7z010clg400-1.yaml -F 0x00000000:0xffffffff -o design.bits -z -y design.bit
> Bitstream size: 2185267 bytes
> Config size: 546279 words
> Number of configuration frames: 5144
> DONE
> \+ python3 /home/verhaegs/eda/code/prjxray/fuzzers/051-imuxlout/generate.py
> Loading bits from design.bits.
> Loading tags from design.txt.
> Compiling segment data.
> touch build/5/specimen_020/OK
> /home/verhaegs/eda/code/prjxray/build/tools/segmatch -m 15 -M 45 -o build/segbits_int_l.db 
> Reading from stding.

and just stays there.
Was repeatable after cleaning up build and building it again.
My OS is Centos7.

**Comment by kgugala** [comment]
#474 fixes this issue
