### ISSUE TITLE
Getting INT_L baseaddrs connected to PSS in Zynq

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#495]
For the xc7z parts, the Processing System is connected to the fabric through the first column of INT tiles. The processing of the INT_L/R base addresses as it is right now is done by propagating the base address of the corresponding CLB/BRAM which they belong to.
As the INT tiles connected to the PSS do not have a belonging site (it should actually be the PSS hard block), we need to find another way to populate the INT tiles base addresses for what regards the xc7z parts.

**Comment by kgugala** [comment]
@acomodi can we close this one?

**Comment by acomodi** [comment]
Yes
