### ISSUE TITLE
05x pip series should reduce todo size on QUICK

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#497]
recently we increased n from 10 to 50 on at least one fuzzer. This significantly slowed down the quick build.  Lets add a check that only does a low number (I'd suggest n=3) for these fuzzers so that they run very quickly

**Comment by tmichalak** [comment]
This has been already implemented:
https://github.com/SymbiFlow/prjxray/blob/master/fuzzers/pip_loop.mk#L3
