### ISSUE TITLE
Fuzzer pre-run sanity check

### ISSUE THREAD

**Issue by natsfr** [SymbiFlow/prjxray#529]
We could add a check of all needed files before running slow fuzzer to avoid failing late in the process.

**Comment by kgugala** [comment]
global fuzzer makefile defines the required dependencies. If you run make for a selected fuzzer from there all the deps should be checked and built if needed

**Comment by kgugala** [comment]
to be more precise you need to run `make fuzzer/run.ok` e.g. `make 074-dump_all/run.ok` will build 74th fuzzer with all the dependencies (072)

**Comment by natsfr** [comment]
Ok I'll try and check but I think there were some miss yesterday.

**Comment by kgugala** [comment]
of course, if a dependency is built for a different chip, the makefile will not detect it

**Comment by natsfr** [comment]
For that point I opened an other Feature request #528 it could be linked :)

**Comment by natsfr** [comment]
See #494
