### ISSUE TITLE
Investigate INT bit changes

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#554]
The latest database output has mostly converged with the previous "good" database output (https://github.com/SymbiFlow/prjxray-db/commit/79aea5dea11a1e9542b4a72a2ddb6e091680f0d5), however some INT bits have changed, and it is unclear which bits were correct:

a_segbits is https://github.com/SymbiFlow/prjxray-db/commit/79aea5dea11a1e9542b4a72a2ddb6e091680f0d5 and b_segbits is the output from running fuzzers @ https://github.com/SymbiFlow/prjxray/commit/f61ccd1f2ae1fc2bb4f5a47ac5a97ca3c7a06ec6

```
--- /tmp/tmp.wKOqa4zelu_a_segbits_int_l.db	2019-01-18 10:25:39.512272473 -0800
+++ /tmp/tmp.kRBFTwQUtG_b_segbits_int_l.db	2019-01-18 10:25:39.528272445 -0800
@@ -608 +608 @@
-INT_L.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
+INT_L.FAN_ALT1.GFAN1 !22_48 !23_48 !24_48 21_48 25_48
@@ -680 +680 @@
-INT_L.FAN_ALT4.GFAN0 !22_08 !23_08 !24_08 21_08 25_08
+INT_L.FAN_ALT4.GFAN0 !00_10 !00_11 !01_09 !01_10 !22_08 !23_08 !24_08 01_14 21_08 25_08
@@ -704 +704 @@
-INT_L.FAN_ALT5.GFAN1 00_14 00_17 21_40 25_40
+INT_L.FAN_ALT5.GFAN1 !22_40 !23_40 !24_40 21_40 25_40
@@ -2027 +2027 @@
-INT_L.LV_L18.LH12 01_08
+INT_L.LV_L18.LH12 01_02 01_08
Comparing segbits_int_r.db
--- /tmp/tmp.kKtZ1ds4Mp_a_segbits_int_r.db	2019-01-18 10:25:39.556272395 -0800
+++ /tmp/tmp.1EycVDAFVY_b_segbits_int_r.db	2019-01-18 10:25:39.572272367 -0800
@@ -584 +584 @@
-INT_R.FAN_ALT0.GFAN0 01_10 01_14 21_00 25_00
+INT_R.FAN_ALT0.GFAN0 !22_00 !23_00 !24_00 21_00 25_00
@@ -608 +608 @@
-INT_R.FAN_ALT1.GFAN1 00_14 00_17 21_48 25_48
+INT_R.FAN_ALT1.GFAN1 !22_48 !23_48 !24_48 21_48 25_48
@@ -656 +656 @@
-INT_R.FAN_ALT3.GFAN1 00_14 00_17 21_56 25_56
+INT_R.FAN_ALT3.GFAN1 !22_56 !23_56 !24_56 21_56 25_56
@@ -697 +697 @@
-INT_R.FAN_ALT5.BYP_BOUNCE1 20_40 24_40 25_15
+INT_R.FAN_ALT5.BYP_BOUNCE1 !22_40 !23_40 !25_40 20_40 24_40
@@ -704 +704 @@
-INT_R.FAN_ALT5.GFAN1 !22_40 !23_40 !24_40 00_20 01_43 21_40 25_40
+INT_R.FAN_ALT5.GFAN1 !22_40 !23_40 !24_40 21_40 25_40
@@ -1991 +1991 @@
-INT_R.LV18.LH12 01_08
+INT_R.LV18.LH12 01_02 01_08
```

**Comment by litghost** [comment]
Because the bits that have moved around don't obvious belong to another tile that is shared with INT, it's not clear if the new bits are more correct.

**Comment by mcmasterg** [comment]
Taking this as an example:

```
-INT_R.FAN_ALT3.GFAN1 00_14 00_17 21_56 25_56
+INT_R.FAN_ALT3.GFAN1 !22_56 !23_56 !24_56 21_56 25_56
```

Investigate why the !'s have been added. Generally !'s are added as part of a bit being present in a group without others from that group. However, both of those bits (21_56 25_56) were previously present, implying it should have also added the !'s before. Possibly this is a regression in the masking code.
