### ISSUE TITLE
Zynq ROI does not include IO column

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/prjxray#558]
while this https://github.com/SymbiFlow/prjxray/pull/557 fixed 058 it broke 005. This is because the new ROI does not include any IO. In the zynq part we use all the IOs are on the right side so there is no option to include them in ROI without including hclks after hclk_brk. Including those hclk's breaks 058.

**Comment by litghost** [comment]
For now, does it make sense to have 058 to exclude tiles?
