### ISSUE TITLE
Check out of bound bits

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#575]
There are some bits which happen to be out-of-bound, specifically for what regards the zynq7 db. There should be an additional control that checks whether there are some out of bound bits.

For example:
`INT_L.FAN_ALT0.LOGIC_OUTS_L22 !22_00 !23_00 !25_00 21_00 24_00 30_45` 

INT tiles have no more than 28 frames, and the last bit is clearly out of bound.

**Comment by litghost** [comment]
#574 should prevent this from happening, but check db should also be augmented to detect it.
