### ISSUE TITLE
fuzzer 019 produces duplicate tags

### ISSUE THREAD

**Issue by kgugala** [SymbiFlow/prjxray#579]
two consecutive runs gave:

```
WARNING: got duplicate tag CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI                                              
Orig line: CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI 00_00 24_00                                                
New line : CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI 00_00 
```
tested on artix

**Comment by litghost** [comment]
That fuzzer is still on N = 1 (https://github.com/SymbiFlow/prjxray/blob/master/fuzzers/019-clb-ndi1mux/Makefile#L1)

Try increasing N to 3 first.  I've found that lowers the probability of a bad bit significantly.

**Comment by litghost** [comment]
There is logic in 019 "checkdb", but that logic isn't wired into the root makefile.  Maybe that is the bug?

**Comment by kgugala** [comment]
with N=3 I still get the same error

**Comment by litghost** [comment]
Wait, I may have misunderstood.  This issue is backwards.  The "Orig line" is wrong, so the database in your tree is corrupt.  Fuzzer 019 is returning the correct answer ("00_00" is correct, "00_00 24_00" is wrong).

https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/segbits_clblm_l.db#L352

**Comment by kgugala** [comment]
ok so the first run with N=1 must have generated incorrect DB entry. I'll set up a test where I'll build the 019 over and over for a few hour. If that one passes with N=3, we can assume this solves the problem.

**Comment by kgugala** [comment]
with N=3 It's been running for 10h without fail. I'll open a PR
