### ISSUE TITLE
`python3 utils/checkdb.py --db-root database/artix7` broken?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#583]
With the latest database it seems like `utils/checkdb.py` is broken (or now takes a *very* long time).

**Comment by litghost** [comment]
Is this still an issue?

**Comment by acomodi** [comment]
I am looking at this issue. It seems that it takes infinite time because it iterates over all the tiles (`~18000` entries). I have checked it and it should never end up in an infinite loop. I am trying to see if it can be somehow optimized

**Comment by acomodi** [comment]
This can be closed thanks to https://github.com/SymbiFlow/prjxray/pull/631
