### ISSUE TITLE
Undefined variable 'GENERATE_FLAGS'

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#592]
I'm seeing this warning during builds;
```
/tmpfs/src/github/symbiflow-prjxray-presubmit-db-zynq7/utils/top_generate.mk:24: warning: undefined variable 'GENERATE_FLAGS'
```

**Comment by mithro** [comment]
@tmichalak What is the status here?

**Comment by tmichalak** [comment]
@mithro: I recall seeing this error a while back, but can't see any of those in the recent logs. Will keep my eyes open.

**Comment by tmichalak** [comment]
Haven't seen this for a while. Closing for now.
