### ISSUE TITLE
-j option not getting passed down through some fuzzer scripts

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#626]
Make automatically detects commands that start with `$(MAKE)` and passes the jobserver information down to the submake process. If make is calling another tool which then calls make, it needs to be prefixed with a `+` symbol.

For example;
```Makefile

target1:
	# Make doesn't know to pass jobserver / -j information down to this script.
	shell_script_which_runs_make.sh
```

```Makefile

target1:
	# Make now knows that this command will launch submake processes.
	+shell_script_which_runs_make.sh
```

We need to audit all our fuzzers are doing the right thing here. You will get the following error message otherwise;
```
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

**Comment by mithro** [comment]
@tmichalak Is this done now?

**Comment by tmichalak** [comment]
@mithro yes, all necessary changes have been merged a while back and I didn't see any of the warning messages for quite some time.

**Comment by mithro** [comment]
Great!
