### ISSUE TITLE
Unstable output from 042 fuzzer

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#657]
ERROR: 1 collisions
  00400c87_096_22: had INT_R_X25Y97.INT_R.NR1BEG3.EL1END3, got CLK_BUFG_BOT_R_X67Y100.CLK_BUFG_BOT_R.BUFGCTRL.BUFGCTRL_X0Y15.PRESELECT_I1

**Comment by litghost** [comment]
```CLK_BUFG_BOT_R.BUFGCTRL.BUFGCTRL_X0Y15.PRESELECT_I1 07_118 26_252```

Segmatch should be using "-c 1"

**Comment by litghost** [comment]
Given that the same count is already 50, this fuzzer likely needs additional stimulus or a bitfilter.

**Comment by litghost** [comment]
This fuzzer has been persistently unstable, disabling for now.

**Comment by tmichalak** [comment]
I reran the fuzzer several time and I was getting the following result consistently:
<pre>
WARNING: got duplicate tag CLK_BUFG_TOP_R.BUFGCTRL.BUFGCTRL_X0Y6.PRESELECT_I1
  Orig line: CLK_BUFG_TOP_R.BUFGCTRL.BUFGCTRL_X0Y6.PRESELECT_I1 26_108
  New line : CLK_BUFG_TOP_R.BUFGCTRL.BUFGCTRL_X0Y6.PRESELECT_I1 18_192 26_108
</pre>
However, I noticed that the last change to the Makfile (commit d9251986 by @litghost ) reduced the specimen count to 40. 
When I changed it back to 50 I started to consistently get solely bit ``26_108`` for ``CLK_BUFG_TOP_R.BUFGCTRL.BUFGCTRL_X0Y6.PRESELECT_I1`` and pushdb finished without any conflicts.
Maybe we should restore the count to 50 and enable the fuzzer in master?

**Comment by litghost** [comment]
Try a PR at 50, but I believe it was still unstable.

**Comment by litghost** [comment]
In theory https://github.com/SymbiFlow/prjxray/pull/695 fixed this.
