### ISSUE TITLE
Unstable output in INT fuzzers

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#658]
ERROR: 1 collisions
  00001518_058_16: had INT_L_X18Y78.INT_L.FAN_ALT1.SW2END2, got BRAM_L_X18Y75.BRAM_L.RAMB18_Y0.FIFO_MODE

**Comment by acomodi** [comment]
What if we expand all the FAN_ALT* and not only the GFAN* in fuzzer 054-pip-fan-alt?

**Comment by litghost** [comment]
Still determining if this is a bug with the INT or BRAM fuzzer.

**Comment by litghost** [comment]
Looks like an instability in the BRAM FIFO config fuzzer:

BRAM_L.RAMB18_Y0.FIFO_MODE 24_240 27_150

**Comment by acomodi** [comment]
Ok, probably more stimuli or stricter segmatch arguments are needed to 029
