### ISSUE TITLE
BRAM SDP_WRITE_WIDTH_36 not found when building bram_sdp_test

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/prjxray#677]
This was produced by running `make bram_sdp_test_bin`. (commit https://github.com/SymbiFlow/symbiflow-arch-defs/commit/59370fd9b7a73fbd711693650a00d4b258fc0e86)

```
prjxray.fasm_assembler.FasmLookupError: Segment DB BRAM_L, key BRAM_L.RAMB18_Y1.SDP_WRITE_WIDTH_36 not found from line 'BRAM_L_X6Y125.RAMB18_Y1.SDP_WRITE_WIDTH_36 = 1'b1'
```

This will prevent also `picosoc` to be built because it uses the `SDP_WRITE_WIDTH_36` feature as well

**Comment by litghost** [comment]
These bits were added to 025 in https://github.com/SymbiFlow/prjxray/pull/674
