### ISSUE TITLE
`028-fifo-config` and `029-bram-fifo-config`?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#688]
There seems to be both `028-fifo-config` and `029-bram-fifo-config`? Are they the same or different?

**Comment by litghost** [comment]
028-fifo-config is FIFO only, 029-bram-fifo-config BRAM versus FIFO config.  029 does not fit easily into 025 or 028, hence it's own fuzzer.

**Comment by mithro** [comment]
README.md would help?
