### ISSUE TITLE
roi_harness on zynq should have PS7 cell instantiated?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#704]
```
WARNING: [DRC ZPS7-1] PS7 block required: The PS7 cell must be used in this Zynq design in order to enable correct default configuration.
```

**Comment by kgugala** [comment]
I don't think it is necessary. Vivado complains about it, but the designs work fine.
For the time being we don't have PS7 tech map in Yosys, so I'd leave the roi_harness for Zynq wihtout PS7 cell.

**Comment by tmichalak** [comment]
The warning message turned out to be irrelevant. Closing.
