### ISSUE TITLE
fuzzers/054-gfan results change from run to run

### ISSUE THREAD

**Issue by kc8apf** [SymbiFlow/prjxray#77]
I started two database builds from the exact same, clean source tree.  The GFAN bits are different between the two resulting databases:

--- db-run1/raw/artix7/segbits_int_l.db	2018-02-05 17:29:16.000000000 -0800
+++ db-run2/raw/artix7/segbits_int_l.db	2018-02-05 14:02:38.000000000 -0800
@@ -703,7 +703,7 @@
 INT_L.FAN_ALT5.ER1END2 !23_40 17_40 22_40 24_40 25_40
 INT_L.FAN_ALT5.FAN_BOUNCE1 !22_40 20_40 23_40 24_40 25_40
 INT_L.FAN_ALT5.FAN_BOUNCE_S3_0 !23_40 20_40 22_40 24_40 25_40
-INT_L.FAN_ALT5.GFAN1 !22_40 !23_40 !24_40 21_40 25_40
+INT_L.FAN_ALT5.GFAN1 !00_18 !00_19 !01_13 !22_40 !23_40 !24_40 00_14 00_17 21_40 25_40
 INT_L.FAN_ALT5.LOGIC_OUTS_L10 !22_40 21_40 23_40 24_40 25_40
 INT_L.FAN_ALT5.LOGIC_OUTS_L16 !22_40 !23_40 !25_40 21_40 24_40
 INT_L.FAN_ALT5.LOGIC_OUTS_L6 !23_40 21_40 22_40 24_40 25_40

**Comment by cliffordwolf** [comment]
That's a signal/noise ratio problem. We might need to up the number on specimens used for this fuzzer.
