### ISSUE TITLE
Add feature for each input of a mux

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/prjxray#817]
Example:

```
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI 00_00
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BDI1 !00_00
CLBLM_L.SLICEM_X0.BLUT.DI1MUX.BI 00_20
CLBLM_L.SLICEM_X0.BLUT.DI1MUX.DI !00_20
```

This makes it easier to read, and will allow detecting conflicts.

**Comment by mithro** [comment]
A grep inside https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/segbits_clblm_l.db gives;
```
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI 00_00
CLBLM_L.SLICEM_X0.BLUT.DI1MUX.BI 00_20
CLBLM_L.SLICEM_X0.CLUT.DI1MUX.CI 01_43
```

Should this really be;
```
CLBLM_L.SLICEM_X0.DI1MUX.AI 00_00
CLBLM_L.SLICEM_X0.DI1MUX.BI 00_20
CLBLM_L.SLICEM_X0.DI1MUX.CI 01_43
```

**Comment by mithro** [comment]
This seems to be done by the https://github.com/SymbiFlow/prjxray/tree/master/fuzzers/019-clb-ndi1mux fuzzer...

**Comment by mithro** [comment]
https://github.com/SymbiFlow/prjxray/tree/master/fuzzers/019-clb-ndi1mux/minitest has some more comments?

**Comment by mithro** [comment]
BTW If it is the missing zero bits -- then bits.dbf file is what should be used I think?

See https://github.com/SymbiFlow/prjxray/blob/36e6290ec6638f88962d23582a3c5329e6d665d3/fuzzers/036-iob-ologic/bits.dbf#L1-L3 and https://github.com/SymbiFlow/prjxray/blob/36e6290ec6638f88962d23582a3c5329e6d665d3/fuzzers/036-iob-ologic/Makefile#L9-L11

**Comment by litghost** [comment]
> A grep inside https://github.com/SymbiFlow/prjxray-db/blob/master/artix7/segbits_clblm_l.db gives;
> 
> ```
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI 00_00
> CLBLM_L.SLICEM_X0.BLUT.DI1MUX.BI 00_20
> CLBLM_L.SLICEM_X0.CLUT.DI1MUX.CI 01_43
> ```
> 
> Should this really be;
> 
> ```
> CLBLM_L.SLICEM_X0.DI1MUX.AI 00_00
> CLBLM_L.SLICEM_X0.DI1MUX.BI 00_20
> CLBLM_L.SLICEM_X0.DI1MUX.CI 01_43

This is wrong, the current definition is correct, we are missing the inverted versions.

**Comment by mithro** [comment]
So for the `ADI1MUX` both `BDI1` and the `BMC31` values are missing?

![image](https://user-images.githubusercontent.com/21212/59806786-79f97d00-92aa-11e9-99c4-367b75188f16.png)

```
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI     00_00
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BDI1  !00_00
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BMC31  ?????
```

https://github.com/SymbiFlow/prjxray/tree/master/fuzzers/019-clb-ndi1mux/minitest

**Comment by litghost** [comment]
> So for the `ADI1MUX` both `BDI1` and the `BMC31` values are missing?
> 
> ![image](https://user-images.githubusercontent.com/21212/59806786-79f97d00-92aa-11e9-99c4-367b75188f16.png)
> 
> ```
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI     00_00
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BDI1  !00_00
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BMC31  ?????
> ```
> 
> https://github.com/SymbiFlow/prjxray/tree/master/fuzzers/019-clb-ndi1mux/minitest
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/34549754?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[SymbiFlow/prjxray](https://github.com/SymbiFlow/prjxray)**Documenting the Xilinx 7-series bit-stream format. - SymbiFlow/prjxray

No, as a said above, the database is correct.  There is no bit at all for the BMC31 or BDI1 port of the mux.  The likely table is:
 ``SRL`` -> ``ADI1MUX.BMC31``
``RAM`` -> ``ADI1MUX.BDI1``
``ADI1MUX.AI`` -> ``ADI1MUX.AI``

**Comment by mithro** [comment]
So, this would be the real info?
```
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI              00_00
# Slice configured as SRL == BCM31, RAM == BDI1
CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BDI1_OR_BMC31  !00_00
```

**Comment by litghost** [comment]
> So, this would be the real info?
> 
> ```
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.AI              00_00
> # Slice configured as SRL == BCM31, RAM == BDI1
> CLBLM_L.SLICEM_X0.ALUT.DI1MUX.BDI1_OR_BMC31  !00_00
> ```

Yes

**Comment by mithro** [comment]
@litghost Is this done now with #900 or do we need a list of other muxes which need to be done?

**Comment by litghost** [comment]
I only added bits for the ADI mux, I believe there are others.  For example, I know the CARRY [ABCD]CY mux needs this treatment.

**Comment by mithro** [comment]
I opened #939 to get someone to go through and figure which other muxes need this treatment (and then hopefully fix them).

Closing this issue.
