### ISSUE TITLE
Fix compilation errors with clang

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/prjxray#830]
In file included from /home/dusty/src/symbiflow-arch-defs/third_party/prjxray/lib/xilinx/xc7series/configuration_bus.cc:1:
In file included from /home/dusty/src/symbiflow-arch-defs/third_party/prjxray/lib/include/prjxray/xilinx/xc7series/configuration_bus.h:10:
/home/dusty/src/symbiflow-arch-defs/third_party/prjxray/lib/include/prjxray/xilinx/xc7series/configuration_column.h:39:9: error: class 'convert' was previously declared as a struct
      [-Werror,-Wmismatched-tags]
        friend class YAML::convert<ConfigurationColumn>;
               ^
/home/dusty/src/symbiflow-arch-defs/third_party/prjxray/third_party/yaml-cpp/include/yaml-cpp/node/convert.h:28:8: note: previous use is here
struct convert;
       ^
In file included from /home/dusty/src/symbiflow-arch-defs/third_party/prjxray/lib/xilinx/xc7series/configuration_bus.cc:1:
/home/dusty/src/symbiflow-arch-defs/third_party/prjxray/lib/include/prjxray/xilinx/xc7series/configuration_bus.h:45:9: error: class 'convert' was previously declared as a struct
      [-Werror,-Wmismatched-tags]
        friend class YAML::convert<ConfigurationBus>;
               ^
/home/dusty/src/symbiflow-arch-defs/third_party/prjxray/third_party/yaml-cpp/include/yaml-cpp/node/convert.h:28:8: note: previous use is here
struct convert;
       ^
2 errors generated.
make[3]: *** [third_party/prjxray/lib/CMakeFiles/libprjxray.dir/build.make:141: third_party/prjxray/lib/CMakeFiles/libprjxray.dir/xilinx/xc7series/configuration_bus.cc.o] Error 1
make[3]: Leaving directory '/home/dusty/src/symbiflow-arch-defs/build'
make[2]: *** [CMakeFiles/Makefile2:4207: third_party/prjxray/lib/CMakeFiles/libprjxray.dir/all] Error 2
make[2]: Leaving directory '/home/dusty/src/symbiflow-arch-defs/build'
make[1]: *** [CMakeFiles/Makefile2:106854: xc7/tests/bram_shifter/CMakeFiles/bram_shifter_bin.dir/rule] Error 2
make[1]: Leaving directory '/home/dusty/src/symbiflow-arch-defs/build'
make: *** [Makefile:35041: bram_shifter_bin] Error 2
make: Leaving directory '/home/dusty/src/symbiflow-arch-defs/build'

**Comment by mithro** [comment]
I believe this was fixed by https://github.com/SymbiFlow/prjxray/pull/878 ?
