### ISSUE TITLE
Timeout on 053-pip-ctrlin

### ISSUE THREAD

**Issue by tmichalak** [SymbiFlow/prjxray#843]
Fuzzer 053 just like 041 (#784) fails with timeout from time to time for each architecture. 

Example log: https://source.cloud.google.com/results/invocations/e8050c23-234b-45c2-a31f-a8b5c91c8023/log

**Comment by litghost** [comment]
Still failing on master?
https://sponge.corp.google.com/invocation?id=3412779c-1b05-44ee-8c52-b48eb359fa8d&searchFor=

**Comment by tmichalak** [comment]
Working fine on master for quite some time now. Closing.
