### ISSUE TITLE
What is the `CLBLL_L.SLICEL_X0.ADI1MUX`?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#86]
I can't figure out what `CLBLL_L.SLICEL_X0.ADI1MUX` is? 

Is it the `AUSED` mux on the `A` output?

It sounds like it is "*A Data In 1 MUX*"?

**Comment by mithro** [comment]
It looks like this is actually from the `SLICEM`?

**Comment by mithro** [comment]
It also looks like the following are from the SLICEM too....
```
CLBLL_L.SLICEL_X0.CLUT.RAM	31_46
CLBLL_L.SLICEL_X0.CLUT.SMALL	00_28
CLBLL_L.SLICEL_X0.CLUT.SRL	30_46
```

**Comment by mithro** [comment]
@cliffordwolf / @JohnDMcMaster - Any idea why these names from the SLICEM are getting into the SLICEL description?

**Comment by mcmasterg** [comment]
Yes this is wrong. Created PR: https://github.com/SymbiFlow/prjxray/pull/95

**Comment by mithro** [comment]
These should all be fixed now.
