### ISSUE TITLE
SDF output is missing mux timing

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/prjxray#890]
The current BEL timing fuzzer is not documenting BEL routing muxes, e.g. [ABCD]OUTMUX.  For example F7A -> AOUT is at ``bel_d_sm_f7amux_amux``.

**Comment by litghost** [comment]
@kgugala FYI

**Comment by kgugala** [comment]
I can confirm this. The fuzzer uses Vivado's `get_bels` function to get all the BELs inside the processed site. This function returns only regular BELs (not routing bels)

**Comment by kgugala** [comment]
Dumping all the speed_models in a device gets routing bels models. I need to find a way to correlate speed_models with BELs
