### ISSUE TITLE
Document HCLK_CMT config bits

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/prjxray#898]
The HCLK_CMT tile contains:
- HCLK_CMT_MUX interconnect. Bits for this are required to break from the ROI (route clock from IOB to BUFHCE)
- 2xBUFMRCE. Those can route clock between clock regions to other CMT tiles.

Base address of this tile is already known. Having bits for the interconnect should be the priority.

**Comment by tmichalak** [comment]
@litghost @mkurc-ant : Doesn't fuzzer 045-hclk-cmt-pips solve the interconnect bits already?

**Comment by litghost** [comment]
I double checked this, and agree with @tmichalak that the HCLK CMT pips appear solved.  I do not believe at this time any additional bits are required for LiteX, but until LiteX reaches zero, it will be hard to tell.  In the mean time I've moved onto the PLL (which has a bunch of bits).  Hopefully once the PLL bits are documented, it will be clearer if this issue has remaining work.
