### ISSUE TITLE
Convert README.txt to README.md files

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#9]
Markdown is formatted nicer on GitHub.

Lets fix up all our README files to be markdown.

**Comment by mcmasterg** [comment]
All of them? I'm not a fan of this. I primarily view the repo for local use, not github. In that case they are nicer as .txt files

**Comment by mithro** [comment]
Thanks to @unixb0y , the conversion has been done, but now they need a bit of clean up on the formatting. I think they should be formatted this way;

<pre lang="no-highlight"><code>
# CLBnFFMUX Fuzzer

## Purpose

Document nFFMUX family of CLB muxes  

## Algorithm

## Outcome

```
CLB.SLICE_X0.AFFMUX.B0 30_00
CLB.SLICE_X0.AFFMUX.B0 30_00
CLB.SLICE_X0.AFFMUX.B0 30_00
... more lines ...
```

From manual O6 testing ;

```
X0 AOUTMUX O6  
X0 BOUTMUX O6  
```

</code></pre>

which will then render like this;

> # CLBnFFMUX Fuzzer
> ## Purpose
> 
> Document nFFMUX family of CLB muxes  
> 
> ## Algorithm
> 
> ## Outcome
> 
> ```
> CLB.SLICE_X0.AFFMUX.B0 30_00
> CLB.SLICE_X0.AFFMUX.B0 30_00
> CLB.SLICE_X0.AFFMUX.B0 30_00
> ... more lines ...
> ```
> 
> From manual O6 testing ;
> 
> ```
> X0 AOUTMUX O6  
> X0 BOUTMUX O6  
> ```

**Comment by unixb0y** [comment]
Ok @mithro if you want I’ll do that the next days. Didn’t know that was needed but it’s not a problem!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unixb0y** [comment]
Btw, this can be closed now.

**Comment by mithro** [comment]
I think the bullet points still need to be fixed.

**Comment by unixb0y** [comment]
Oh right, I remember.

**Comment by mithro** [comment]
Btw @unixb0y are you student at Uni?

**Comment by unixb0y** [comment]
Yeah I am 😃

**Comment by unixb0y** [comment]
Pull Request is open 😊

**Comment by mithro** [comment]
It is likely that both the [TimVideos](https://code.timvideos.us/summer-of-code/) and [FOSSi Foundation](https://fossi-foundation.org/gsoc18-ideas.html) will definately consider projects related to SymbiFlow for [Google Summer of Code](https://summerofcode.withgoogle.com/).

**Comment by unixb0y** [comment]
Oh, thanks for the hint! I've heard of "Google Summer of Code" but didn't think of participating myself, especially with this project.
Might have a look at it after my exams 😉
