### ISSUE TITLE
Bits for ADI1MUX, BDI1MUX and CDI1MUX

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/prjxray#911]
Recently merged PR https://github.com/SymbiFlow/prjxray/pull/900 allows to have in DB bits for those muxes. The bits are required for SRL32/SRL16 support.

This issue is here to not forget to push those to the DB

**Comment by mithro** [comment]
Looks like these have been included now.

### Artix
https://github.com/SymbiFlow/prjxray-db/commit/84a5ffc0d5f87d57f0fd5cde135edb7a2198212e#diff-0de60774b3b2c1043cb089e5a0ca0d94R354
https://github.com/SymbiFlow/prjxray-db/commit/84a5ffc0d5f87d57f0fd5cde135edb7a2198212e#diff-0de60774b3b2c1043cb089e5a0ca0d94R441
https://github.com/SymbiFlow/prjxray-db/commit/84a5ffc0d5f87d57f0fd5cde135edb7a2198212e#diff-0de60774b3b2c1043cb089e5a0ca0d94R534

### Zynq
https://github.com/SymbiFlow/prjxray-db/commit/2d9308a8d8f54c0ffc34f12c0c40e11676fd0774#diff-a8616afb89051e8a009ab9defd46f0dcR354
https://github.com/SymbiFlow/prjxray-db/commit/2d9308a8d8f54c0ffc34f12c0c40e11676fd0774#diff-a8616afb89051e8a009ab9defd46f0dcR441
https://github.com/SymbiFlow/prjxray-db/commit/2d9308a8d8f54c0ffc34f12c0c40e11676fd0774#diff-a8616afb89051e8a009ab9defd46f0dcR530
