### ISSUE TITLE
Documents bits for DOUTMUX.AMC31 input

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/prjxray#927]
The `Q31` output of one of `SRLC32E`s can be routed outside SLICE through the `AMC31` input of the `DOUTMUX`.

The original assumption was that setting no bits would make the `DOUTMUX` select the `AMC31` input.
However for a minitest regarding two designs in which one used the `Q31` and the other did not, two unknown bits were identified. Also a preliminary implementation of `SRL32` in symbiflow led to a conclusion that the `DOUTMUX` does not defaults to `AMC31` input.

Unknown bits (presumably for CLBLM_R_X3Y0) are:
```
{ unknown_bit = "0040019e_3_20", unknown_segment = "0x00400180", unknown_segbit = "30_116" }
{ unknown_bit = "0040019e_3_25", unknown_segment = "0x00400180", unknown_segbit = "30_121" }
```

**Comment by mkurc-ant** [comment]
Confirmed. When I duplicated the design (two `SRLC32E`) I have now 4 unknown bits. Should be for CLBLM_R_X3Y0 and CLBLM_R_X3Y2:

```
{ unknown_bit = "0040019e_3_20", unknown_segment = "0x00400180", unknown_segbit = "30_116" }
{ unknown_bit = "0040019e_3_25", unknown_segment = "0x00400180", unknown_segbit = "30_121" }
{ unknown_bit = "0040019e_7_20", unknown_segment = "0x00400180", unknown_segbit = "30_244" }
{ unknown_bit = "0040019e_7_25", unknown_segment = "0x00400180", unknown_segbit = "30_249" }
```

**Comment by litghost** [comment]
Good investigation, makes sense.

**Comment by mkurc-ant** [comment]
https://github.com/SymbiFlow/prjxray/pull/933
